name: Java CI with Maven

on:
  push:
    branches: [ "main", "master" ]  # Runs when code is pushed
  pull_request:
    branches: [ "main", "master" ]  # Runs on PRs
  workflow_dispatch:  # Allows manual trigger

jobs:
  checkout-and-build:
    runs-on: ubuntu-latest  # Runner environment

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Fetch latest code

      - name: List Files
        run: ls -la  # Verify files are checked out

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
